# Generated by Django 4.0.4 on 2022-04-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_t', models.CharField(max_length=100)),
                ('status_t', models.CharField(default='Not Done', max_length=10)),
            ],
        ),
    ]
