# Generated by Django 4.0.4 on 2022-04-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todo_item',
            new_name='ToDoItem',
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='status_t',
            new_name='todo_status',
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='text_t',
            new_name='todo_text',
        ),
    ]
